presubmits:
  - name: trigger-tfe-speculative-plan
    decorate: true
    always_run: true
    skip_report: true
    spec:
      containers:
        - image: alpine:latest
          command:
            - sh
            - -c
            - echo $REPO_OWNER/$REPO_NAME\#$PULL_NUMBER
