workspaces:
  - organization: jgiannuzzi
    name: tf
    show_skipped: true
    policy:
      approval:
        - lgtm
  - organization: jgiannuzzi
    name: tf2
    branch: develop
    policy:
      approval:
        - anything goes

approval_rules:
  - name: lgtm
    options:
      invalidate_on_push: true
      request_review:
        enabled: true
      methods:
        comments:
          - "lgtm"
          - "LGTM"
        github_review: false
    requires:
      count: 1
      teams:
        - "jgiannuzzi-org/tf-approvers"
  - name: anything goes
