workspaces:
  - organization: jgiannuzzi
    name: tf
    policy:
      approval:
        - lgtm

approval_rules:
  - name: lgtm
    options:
      invalidate_on_push: true
      request_review:
        enabled: true
      methods:
        comments:
          - "lgtm"
          - "LGTM"
        github_review: false
    requires:
      count: 1
      teams:
        - "jgiannuzzi-org/tf-approvers"
